export const ADD_TODO_LOADING ="ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS ="ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE ="ADD_TODO_FAILURE";

export const GET_TODO_LOADING ="GET_TODO_LOADING";
export const GET_TODO_SUCCESS ="GET_TODO_SUCCESS";
export const GET_TODO_FAILURE ="GET_TODO_FAILURE";

export const TOGGLE_TODO = "TOGGLE_TODO";
export const DELETE_TODO = "DELETE_TODO";