export const ADD_TODO_FAILED="ADD_TODO_FAILED";
export const ADD_TODO_LOADING="ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS";

export const CHANGE_TODO_LOADING = "CHANGE_TODO_LOADING";
export const CHANGE_TODO_SUCCESS = "CHANGE_TODO_SUCCESS";
export const CHANGE_TODO_FAILED = "CHANGE_TODO_FAILED";

export const REMOVE_TODO_LOADING = "REMOVE_TODO_LOADING";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAILED = "REMOVE_TODO_FAILED";


export const GET_TODOS_SUCCESS="GET_TODOS_SUCCESS";
export const GET_TODOS_LOADING="GET_TODOS_LOADING";
export const GET_TODOS_FAILED="GET_TODOS_FAILED";